### ISSUE TITLE
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setups'

### ISSUE THREAD

**Issue by AlePerla** [midstar/homeassistant_tuya_with_bht-002_support#2]
I get this error after copying the folder into home assistant custom_components and reinstalling (and configuring) Tuya integration:
`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/tuya/__init__.py", line 126, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setups'`

Running on Home Assistant 2022.7.5 Core

Thank you for your effort anyway, I think a custom "scaling" option inside the integration would be great to fix device errors

**Comment by midstar** [comment]
I have only tested the custom component with HA 2022.9.x and 2022.10.x. would it be possible for you to upgrade?

**Comment by AlePerla** [comment]
I did not have an update on the frontend so I haven't noticed the newer versions.
Updated HA and it works perfectly. My bad.
Thanks again

**Comment by midstar** [comment]
Pefect. Enjoy :-)
