### ISSUE TITLE
Other Tuya Thermostat - Entity information

### ISSUE THREAD

**Issue by Elhoj** [midstar/homeassistant_tuya_with_bht-002_support#3]
Hi 
I have another Tuya thermostat 
(https://www.amazon.ae/gp/product/B091FTXGRY/ref=ppx_yo_dt_b_asin_title_o04_s00?ie=UTF8&psc=1) 
with this Product Identity:

    "name": "Thermostat Livingroom",
    "model": "",
    "category": "wk",
    "product_id": "N8bUqOZ8HBQjU0K0",
    "product_name": "\u67cf\u76ca\u52a0\u6e29\u63a7\u5668\uff08\u7a7a\u8c03\uff09  "

With the original Tuya integration the temperature shown in Home Assistant is 5 time less than what it should be  (so when it should be 25 C - Home Assistant shows 5.0)

Furthermore I don't quite understand **Step 3** - could you maybe explain it in a little more detail? 

How much am I uploading to my Home Assistant is it "just" these files: 
https://github.com/midstar/homeassistant_core/tree/tuya_BHT-002_thermostat_workaround/homeassistant/components/tuya
or is it much more?

When Home Assistant is updated in the future - can I without any issues update?

In **Step 4** - you are talking about  "a version key/value pair" is that this:   "version": "1.0.0"

Thanks in advance
Carsten

This is the information I get from Tuya regarding the Thermostat:
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2022.11.4",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.7",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Asia/Dubai",
    "os_name": "Linux",
    "os_version": "5.15.74",
    "supervisor": "2022.11.2",
    "host_os": "Home Assistant OS 9.3",
    "docker_version": "20.10.18",
    "chassis": "vm",
    "run_as_root": true
  },
  "custom_components": {},
  "integration_manifest": {
    "domain": "tuya",
    "name": "Tuya",
    "documentation": "https://www.home-assistant.io/integrations/tuya",
    "requirements": [
      "tuya-iot-py-sdk==0.6.6"
    ],
    "dependencies": [
      "ffmpeg"
    ],
    "codeowners": [
      "@Tuya",
      "@zlinoliver",
      "@frenck"
    ],
    "config_flow": true,
    "iot_class": "cloud_push",
    "dhcp": [
      {
        "macaddress": "105A17*"
      },
      {
        "macaddress": "10D561*"
      },
      {
        "macaddress": "1869D8*"
      },
      {
        "macaddress": "381F8D*"
      },
      {
        "macaddress": "508A06*"
      },
      {
        "macaddress": "68572D*"
      },
      {
        "macaddress": "708976*"
      },
      {
        "macaddress": "7CF666*"
      },
      {
        "macaddress": "84E342*"
      },
      {
        "macaddress": "D4A651*"
      },
      {
        "macaddress": "D81F12*"
      }
    ],
    "integration_type": "hub",
    "loggers": [
      "tuya_iot"
    ],
    "is_built_in": true
  },
  "data": {
    "endpoint": "https://openapi.tuyaeu.com",
    "auth_type": 0,
    "country_code": "971",
    "app_type": "smartlife",
    "mqtt_connected": null,
    "disabled_by": null,
    "disabled_polling": false,
    "name": "Thermostat Livingroom",
    "model": "",
    "category": "wk",
    "product_id": "N8bUqOZ8HBQjU0K0",
    "product_name": "\u67cf\u76ca\u52a0\u6e29\u63a7\u5668\uff08\u7a7a\u8c03\uff09  ",
    "online": false,
    "sub": false,
    "time_zone": "+04:00",
    "active_time": "2022-11-30T10:00:53+00:00",
    "create_time": "2022-11-30T10:00:53+00:00",
    "update_time": "2022-11-30T10:00:53+00:00",
    "function": {
      "switch": {
        "type": "Boolean",
        "value": {}
      },
      "temp_set": {
        "type": "Integer",
        "value": {
          "unit": "\u2103",
          "min": 10,
          "max": 70,
          "scale": 1,
          "step": 5
        }
      },
      "mode": {
        "type": "Enum",
        "value": {
          "range": [
            "auto",
            "manual"
          ]
        }
      },
      "eco": {
        "type": "Boolean",
        "value": {}
      },
      "child_lock": {
        "type": "Boolean",
        "value": {}
      }
    },
    "status_range": {
      "switch": {
        "type": "Boolean",
        "value": {}
      },
      "temp_set": {
        "type": "Integer",
        "value": {
          "unit": "\u2103",
          "min": 10,
          "max": 70,
          "scale": 1,
          "step": 5
        }
      },
      "temp_current": {
        "type": "Integer",
        "value": {
          "unit": "\u2103",
          "min": 0,
          "max": 100,
          "scale": 1,
          "step": 5
        }
      },
      "mode": {
        "type": "Enum",
        "value": {
          "range": [
            "auto",
            "manual"
          ]
        }
      },
      "eco": {
        "type": "Boolean",
        "value": {}
      },
      "child_lock": {
        "type": "Boolean",
        "value": {}
      }
    },
    "status": {
      "switch": true,
      "temp_set": 45,
      "temp_current": 52,
      "mode": "manual",
      "eco": false,
      "child_lock": false
    },
    "home_assistant": {
      "name": "Thermostat",
      "name_by_user": null,
      "disabled": false,
      "disabled_by": null,
      "entities": [
        {
          "disabled": false,
          "disabled_by": null,
          "entity_category": null,
          "device_class": null,
          "original_device_class": null,
          "icon": null,
          "original_icon": null,
          "unit_of_measurement": null,
          "state": {
            "entity_id": "climate.thermostat",
            "state": "unavailable",
            "attributes": {
              "hvac_modes": [
                "off",
                "heat_cool",
                "heat_cool"
              ],
              "min_temp": 1.0,
              "max_temp": 7.0,
              "target_temp_step": 0.5,
              "friendly_name": "Thermostat",
              "supported_features": 1
            },
            "last_changed": "2022-11-30T10:00:56.595617+00:00",
            "last_updated": "2022-11-30T10:00:56.595617+00:00"
          }
        }
      ]
    }
  }
}

**Comment by midstar** [comment]
Hi,

I have now added your Thermostat, based on the ID, into the code. Please try it and let me know if it worked.

Regarding Step 3. Yes, you only need to upload the files in the tuya directory to custom_components.

Regarding Step 4. Yes, it is "version": "1.0.0" that you need to add.

Lastly, since I'm using BHT-002 thermostat myself, and also is trying to keep up to date with latest Home Assistant version, I will try to keep the code up to date. But please add an issue if it is not updated to remind me.

**Comment by Elhoj** [comment]
Hi,

It works very fine - thanks a lot.

There was 2 small issues - one when doing step 6 - there was no text on the "page" where account information etc.. are added (Pic1) 

And second - not all information/functions are available on the "card" for the thermostat (pic2).
I don't know i that is possible at all?

But many thanks again - you made my day :)

Best regards
Carsten

### **Pic1:**
![Text 2022-12-04 003306](https://user-images.githubusercontent.com/104253903/205461000-223991db-5566-4438-ad38-7f6e9aadbda8.jpg)
### **Pic2:**
![Thermostat 2022-12-04 003142](https://user-images.githubusercontent.com/104253903/205461019-f8f685a9-5c6b-439e-8334-eb85bd500e01.jpg)

**Comment by midstar** [comment]
I have now merged the branch with 2022.11.5. It should work as the latest and greatest official version of Home Assistant (except that the temperature is correct).

If you like you can try it out.

**Comment by Elhoj** [comment]
I would like to try - but how do I do that?
(I looked at https://github.com/midstar/homeassistant_core/tree/tuya_BHT-002_thermostat_workaround/homeassistant/components/tuya
but nothing has changed since 2 days ago ..)

**Comment by Elhoj** [comment]
Hi - I updated to Home Assistant 2022.12.8 - and now it look like the Tuya integration of my thermostats dose not work any longer ...

**Comment by swdwi2** [comment]
Thank you so much for sorting this.  Your efforts are much appreciated.

**Comment by midstar** [comment]
Issues solved

**Comment by Elhoj** [comment]
Hi,

I just updated this and now I am back to the same problem as i 2022 - the temperatur is not correct - it is off by a factor of 5.
(I had to update because I got some warnings in my log related to Tuya - se below)
The funny thing is that even though the readings on the card are wrong - my automations are running correct. 

Is it some thing you can help me with?

![image](https://github.com/midstar/homeassistant_tuya_with_bht-002_support/assets/104253903/b037e806-1863-4081-99e1-b4dc3aace2bf)

![image](https://github.com/midstar/homeassistant_tuya_with_bht-002_support/assets/104253903/c4bd42fd-d944-4227-94ed-9dae877b686d)

**Comment by Elhoj** [comment]
As mentioned before my AC automations are running correct but I get errors in the log file. 
They look more less the same - I have attached  two of them (I think the issue is the incorrect displayed temperature)

[homeassistant.components.automation.ac_test.txt](https://github.com/midstar/homeassistant_tuya_with_bht-002_support/files/14396045/homeassistant.components.automation.ac_test.txt)
[homeassistant.components.automation.ac_of_test_1030_0300.txt](https://github.com/midstar/homeassistant_tuya_with_bht-002_support/files/14396046/homeassistant.components.automation.ac_of_test_1030_0300.txt)

**Comment by javifly** [comment]
See the solution in this link: https://github.com/home-assistant/core/issues/104164#issuecomment-1826135261

**Comment by Elhoj** [comment]
Hi javifly,
Thank you for your suggestion – I finally found the time to try your suggested solution (https://github.com/home-assistant/core/issues/104164#issuecomment-1826135261)
It is working - but I get a lot of errors in my log file for all my automations related to Tuya.
![image](https://github.com/midstar/homeassistant_tuya_with_bht-002_support/assets/104253903/c30eb65a-5855-484b-83a8-f10450b8b662)
Unfortunately, I don’t know what the problem is and how to fix it – **maybe you can help**?

I am using a different Tuya AC Controller 
![image](https://github.com/midstar/homeassistant_tuya_with_bht-002_support/assets/104253903/6a2080cb-161c-42b5-aff1-6d0893543a54)
But it is nearly the same as BHT-002 Thermostat

I have attached the log files for first 2 errors (if you need more log files please let me know) 

Best regards
Carsten
[Log file Tuya.txt](https://github.com/midstar/homeassistant_tuya_with_bht-002_support/files/14535976/Log.file.Tuya.txt)
[Log file Tuya 2.txt](https://github.com/midstar/homeassistant_tuya_with_bht-002_support/files/14536011/Log.file.Tuya.2.txt)
