### ISSUE TITLE
Can this be used with regular Tuya enabled

### ISSUE THREAD

**Issue by superdumnezeu** [midstar/homeassistant_tuya_with_bht-002_support#5]
Hello, 

Thanks for making this happen. 

I currently use Tuya for other devices in my network, and I am unable to remove that integration as I would lose the items I have now. 

Is it possible to use this component besides regular Tuya so I can make the thermostat work as expected? 

Thanks

**Comment by midstar** [comment]
Hi. 

It is probably not possible out of the box due to naming conflicts. It migth be possible by just modifying manifest.json name and domain keys. You might need to change the name of the tuya directory as well. Please try and report the results.

**Comment by javifly** [comment]
Would it be possible to install an extra addon to the original tuya or similar to be able to have the thermostats corrected?

**Comment by midstar** [comment]
Unfortunately not right now. You could try the actions suggested above.

**Comment by javifly** [comment]
thanks

**Comment by midstar** [comment]
No updates in the thread. Assuming that the workaround worked.

**Comment by javifly** [comment]
See the solution in this link: https://github.com/home-assistant/core/issues/104164#issuecomment-1826135261
