### ISSUE TITLE
Target temperature not updating in HA 2023.9

### ISSUE THREAD

**Issue by kollarbandibmrg** [midstar/homeassistant_tuya_with_bht-002_support#6]
Hi,
I have been using your fork for quite some time - thanks for that!
However changing HA core from 2022.8.7 to 2023.9.2 brought the issue that the target temperature reading is not updating (in case I change the target temp on the thermostat).
If I try to change the target temp in HA (example: 21°C->22°C), then I see this change on the thermostat, BUT the value is resetted right afterwards in HA (in about 1-2 seconds back to 21°C), meanwhile the thermostat remains with the adjusted temp (22°C).
Current temperature seems to be OK.
Can you check what can cause this issue? Thanks.

**Comment by midstar** [comment]
Hi,

I tried to reproduce your problem, but I don't have the issue. Tested both these scenarios on BHT-002 and another Tuya Thermostat:

- Change target temperature on thermostat -> HA is updated accordingly 
- Change target temperature in HA -> Thermostat is updated accordingly

However, I use HA Core 2023.10.1. Could it be a bug in 2023..9.2? Is the Tuya or SmartLife app working correctly?

**Comment by kollarbandibmrg** [comment]
Hello Joel,
After updating for HA 2023.09.05 solved my problem. So it seems that the 09.02 release was somehow buggy..
(SmartLife app worked well anyway)
Thank you for reaching out.

BR,
Andras

________________________________
Feladó: Joel Midstjärna ***@***.***>
Elküldve: Sunday, October 8, 2023 12:35:35 PM
Címzett: midstar/homeassistant_tuya_with_bht-002_support ***@***.***>
Másolatot kap: kollarbandibmrg ***@***.***>; Author ***@***.***>
Tárgy: Re: [midstar/homeassistant_tuya_with_bht-002_support] Target temperature not updating in HA 2023.9 (Issue #6)


Hi,

I tried to reproduce your problem, but I don't have the issue. Tested both these scenarios on BHT-002 and another Tuya Thermostat:

  *   Change target temperature on thermostat -> HA is updated accordingly
  *   Change target temperature in HA -> Thermostat is updated accordingly

However, I use HA Core 2023.10.1. Could it be a bug in 2023..9.2? Is the Tuya or SmartLife app working correctly?

**Comment by midstar** [comment]
Great! I close the issue
