### ISSUE TITLE
Docker based install - Any idea why not working?

### ISSUE THREAD

**Issue by jweymarn** [midstar/homeassistant_tuya_with_bht-002_support#7]
Hi Midstar!

I have a Docker based HA setup and tried to install this workaround. Not working yet... **Any idea what I'm doing wrong?**

What I did:
1. Removed the standard Tuya integration
2. Placed your [homeassistant/components/tuya](https://github.com/midstar/homeassistant_core/tree/tuya_BHT-002_thermostat_workaround/homeassistant/components/tuya) into my homeassistant/config/custom_components/tuya
3. Added `"version": "1.0.0"` to manifest.json
4. Rebooted my HA
5. Reinstalled the Tuya integration from HA GUI
6. Rebooted HA again

At this stage my assumption is that the Tuya integration should be using the custom_components custom code... but it does not seem to do so.

My MOES thermostats are still off by factor of 5:
![image](https://github.com/midstar/homeassistant_tuya_with_bht-002_support/assets/3504703/e83319d2-d560-41a8-9fc2-5224ff2551b0)

Confirming they are the same product id (IAYz2WK1th0cMLmL) as yours:
![image](https://github.com/midstar/homeassistant_tuya_with_bht-002_support/assets/3504703/1613ecfc-480b-469d-b6b5-30ad73bc827e)

Confirming the file permissions in custom_components should be ok:
![image](https://github.com/midstar/homeassistant_tuya_with_bht-002_support/assets/3504703/e27d9e4f-6879-4170-b32b-fb72182a1ab7)

HA log does not contain anything related to Tuya.... 

If you have any ideas I'd appreciate it a lot!

**Comment by jweymarn** [comment]
Found the problem! It was the manifest,json.

I had added the line at the very end:
`"version": "1.0.0"`

BUT I needed to add a comma at the end of the above line of course 🤦‍♂️. DOH!

![image](https://github.com/midstar/homeassistant_tuya_with_bht-002_support/assets/3504703/fd9d3e58-9a1b-487e-a709-1b9bdeb98235)

Here are the correct climate entities in all their glory:
![image](https://github.com/midstar/homeassistant_tuya_with_bht-002_support/assets/3504703/4c8165a9-8180-4583-9d9b-165f48cebb1b)

If you want to update the instructions for the Docker users:
1. Remove the standard Tuya integration
2. Reboot HA
3. Place [homeassistant/components/tuya](https://github.com/midstar/homeassistant_core/tree/tuya_BHT-002_thermostat_workaround/homeassistant/components/tuya) into your homeassistant/config/custom_components/tuya
4. Add `"version": "1.0.0"` to end of manifest.json. Add a comma to the above line to keep json intact.
5. Reinstall the Tuya integration from HA GUI

**Comment by midstar** [comment]
Nice that you found the problem :-)
